# Generated by Django 5.0.6 on 2024-05-14 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('proyect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.proyect')),
            ],
        ),
    ]
