# Generated by Django 5.0.6 on 2024-05-16 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='proyect',
        ),
        migrations.DeleteModel(
            name='Proyect',
        ),
    ]
