# Generated by Django 5.0.6 on 2024-05-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_task_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='done',
            new_name='completada',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='prioridad',
            field=models.TextField(default='5/07/2024', max_length=5),
            preserve_default=False,
        ),
    ]
