# Generated by Django 5.0.6 on 2024-05-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_task_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='prioridad',
            field=models.CharField(max_length=5),
        ),
    ]
