# Generated by Django 5.0.6 on 2024-05-17 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0007_project_alter_task_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tareas.project'),
            preserve_default=False,
        ),
    ]
