# Generated by Django 5.0.6 on 2024-05-17 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0008_task_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='proyecto',
        ),
    ]
