# Generated by Django 5.0.6 on 2024-05-17 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0010_task_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='proyecto',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='task',
        ),
    ]
