# Generated by Django 5.0.6 on 2024-05-17 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tareas', '0011_remove_task_proyecto_delete_project_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('prioridad', models.CharField(max_length=5)),
                ('fecha', models.DateTimeField()),
                ('completada', models.BooleanField(default=False)),
                ('proyecto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tareas.project')),
            ],
        ),
    ]
