# Generated by Django 5.0.6 on 2024-05-17 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0012_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.project'),
        ),
    ]
